name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, intl
          coverage: none
          cache: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare backend environment
        run: |
          cp .env.example .env
          touch database/database.sqlite
          php artisan key:generate --ansi

      - name: Run database migrations for testing
        run: php artisan migrate --env=testing --force

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Run backend tests
        run: php artisan test

  frontend:
    runs-on: ubuntu-latest
    name: Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test

      - name: Run frontend build
        working-directory: ./frontend
        run: npm run build
